import type { LandingPage } from "./types";

export const REGION_PAGES: LandingPage[] = [
  {
    kind: "region",
    slug: "napa-county",
    name: "Napa County",
    filterValue: "Napa County",
    h1: "Wine Grapes and Bulk Wine from Napa County",
    metaTitle: "Napa County Wine Grapes & Bulk Wine for Sale",
    description: "Buy or sell Napa County wine grapes priced per ton and bulk wine priced per gallon, including confidential lots, with a guide to what to compare.",
    quickAnswer:
      "Napa County is California's most famous wine region and one of its smallest. Napa Valley supplies only about 4 percent of the state's wine grape harvest, with Cabernet Sauvignon covering about 54 percent of its vineyards, so lots are scarce and priced at a premium. Compare the exact appellation and vintage.",
    intro: [
      "Napa Valley is a narrow valley, about 30 miles long and 5 miles across at its widest, with a dry Mediterranean climate and elevations from sea level to about 2,600 feet. Napa Valley Vintners counts 17 approved sub-appellations inside it, from valley-floor areas such as Oakville and Rutherford to mountain areas such as Howell Mountain and Spring Mountain District.",
      "For buyers, the small scale is the main story. The valley supplies only about 4 percent of California's wine grape harvest, and Cabernet Sauvignon alone makes up roughly 54 percent of its planted acreage. That concentration gives Napa a clear identity and keeps supply tight, which is why the same variety can carry very different prices depending on the sub-appellation and the vineyard.",
      "On HarvestLink, Napa County lots are listed by the ton for grapes and by the gallon for bulk wine. Some sellers list confidentially under NDA, in which case you still see the variety, vintage, quantity and price, but not the winery or vineyard name.",
    ],
    facts: [
      { label: "Valley size", value: "About 30 miles long, 5 miles across at its widest" },
      { label: "Sub-appellations", value: "17 approved inside the Napa Valley AVA" },
      { label: "Share of California wine grape harvest", value: "About 4 percent" },
      { label: "Most planted grape", value: "Cabernet Sauvignon, about 54 percent of planted acres" },
      { label: "Climate", value: "Dry Mediterranean" },
    ],
    buyerNotes: [
      "Ask which appellation the fruit or wine comes from. \"Napa County,\" \"Napa Valley\" and a sub-appellation such as Oakville are different things, and label rules apply to each.",
      "Confirm the vintage and, for bulk wine, the lab numbers (ABV, total sulfites) on the actual lot before you agree to buy.",
      "Compare on the same basis: price per ton for grapes, price per gallon for wine, and whether the price is delivered or FOB.",
      "Expect a premium over most other California regions, and check that the premium is for something you can actually claim on your label.",
    ],
    faq: [
      { q: "Is Napa County the same as Napa Valley?", a: "Not exactly. Napa Valley is an American Viticultural Area inside Napa County, and the county has some vineyard land outside the valley appellation. Check the exact appellation a seller lists before you plan to name it on a label." },
      { q: "Why are Napa grapes and bulk wine priced higher?", a: "Supply is small compared with the region's reputation, and Cabernet Sauvignon from named sub-appellations is in strong demand. Price also reflects vintage, farming practice and quality, so compare lots on the same basis." },
      { q: "How do I find Napa lots on HarvestLink?", a: "Use the buttons on this page to see current Napa County grape and bulk wine lots, or save a search and HarvestLink emails you once a day when a new matching lot is listed." },
    ],
    sources: [
      { title: "Napa Valley Vintners: Napa Valley fast facts", url: "https://napavalley.wine/fast-facts" },
      { title: "Wikipedia: Napa Valley AVA", url: "https://en.wikipedia.org/wiki/Napa_Valley_AVA" },
    ],
    related: ["why-napa-valley-wine-is-special", "what-is-terroir", "how-to-buy-wine-grapes"],
    alsoSee: ["sonoma-county", "cabernet-sauvignon", "chardonnay", "mendocino-county"],
    image: "/images/landing/napa-county.webp",
    imageAlt: "Long rows of autumn vines stretching across a valley floor toward distant hills in Napa Valley",
  },
  {
    kind: "region",
    slug: "sonoma-county",
    name: "Sonoma County",
    filterValue: "Sonoma County",
    h1: "Wine Grapes and Bulk Wine from Sonoma County",
    metaTitle: "Sonoma County Wine Grapes & Bulk Wine for Sale",
    description: "Find Sonoma County wine grapes by the ton and bulk wine by the gallon, from Chardonnay and Pinot Noir to Zinfandel, including confidential lots.",
    quickAnswer:
      "Sonoma County has more than 49,000 acres of vineyards, 19 appellations and over 60 grape varieties, but seven varieties make up more than 90 percent of plantings, led by Chardonnay and Pinot Noir. That mix gives buyers real choice of style and price. Ask for the specific appellation.",
    intro: [
      "Sonoma County is larger and more varied than its neighbor Napa. Sonoma County Winegrowers reports more than 49,000 acres of vineyards, over 750 growers, 180 bonded wineries and 19 appellations, and says 95 percent of vineyards are family owned. The range of conditions runs from cool, foggy coastal sites to warm inland valleys.",
      "Seven varieties account for more than 90 percent of plantings. Chardonnay leads at about 15,500 acres, followed by Pinot Noir at about 13,000 and Cabernet Sauvignon at about 12,700. Zinfandel (4,760), Merlot (4,200), Sauvignon Blanc (2,600) and Syrah (1,380) complete the group. That breadth means a buyer can source sparkling base, cool-climate Pinot and Chardonnay, old-vine Zinfandel or Cabernet from one county.",
      "Sonoma County lots on HarvestLink are listed by the ton for grapes and by the gallon for bulk wine, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Vineyard acres", value: "More than 49,000" },
      { label: "Growers and bonded wineries", value: "More than 750 growers, 180 bonded wineries" },
      { label: "Appellations", value: "19" },
      { label: "Largest plantings", value: "Chardonnay (about 15,500 acres), Pinot Noir (about 13,000), Cabernet Sauvignon (about 12,700)" },
      { label: "Family-owned vineyards", value: "95 percent" },
    ],
    buyerNotes: [
      "Name the appellation you need. A Sonoma Coast Pinot Noir and a valley-floor Pinot Noir are very different lots, and the label rules differ too.",
      "For cool-climate varieties, ask about harvest timing and brix: sites near the coast often pick later and lower in sugar than inland sites.",
      "For Zinfandel, ask the vine age. Old-vine fruit is a selling point, but only if the grower can document it.",
      "Ask whether the vineyard holds a sustainability or organic certification, and request the certificate.",
    ],
    faq: [
      { q: "Which varieties are most planted in Sonoma County?", a: "Chardonnay is the most planted at about 15,500 acres, then Pinot Noir at about 13,000 and Cabernet Sauvignon at about 12,700, according to Sonoma County Winegrowers." },
      { q: "Is Sonoma County wine cheaper than Napa?", a: "Often, but not always. Price depends on the variety, the appellation, the vintage and the quality of the specific lot. Compare lots on the same basis instead of assuming by region." },
      { q: "Can I buy Sonoma County bulk wine without knowing the winery?", a: "Yes. Some sellers list under NDA, so their name and vineyard are hidden while the variety, vintage, quantity, ABV and price are shown. Ask for samples and lab analysis from the actual lot." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
    ],
    related: ["how-to-buy-wine-grapes", "organic-biodynamic-sustainable-wine-labels", "how-to-buy-bulk-wine"],
    alsoSee: ["napa-county", "pinot-noir", "chardonnay", "zinfandel"],
    image: "/images/landing/sonoma-county.webp",
    imageAlt: "Vineyard rows with yellow mustard flowers growing between the vines on a green hillside",
  },
  {
    kind: "region",
    slug: "mendocino-county",
    name: "Mendocino County",
    filterValue: "Mendocino County",
    h1: "Wine Grapes and Bulk Wine from Mendocino County",
    metaTitle: "Mendocino County Wine Grapes & Bulk Wine for Sale",
    description: "Source Mendocino County wine grapes and bulk wine, a region with a high share of organic vineyards, from Pinot Noir to Zinfandel and Cabernet.",
    quickAnswer:
      "Mendocino County has about 17,000 planted acres across 12 appellations, and Mendocino Winegrowers reports that about a quarter of its grapes are certified organic. That is about a third of California's organic wine grape acreage. It is a strong place to look for organic fruit and wine.",
    intro: [
      "Mendocino is one of California's larger wine counties by area, yet grapes cover only about 0.8 percent of the land. Mendocino Winegrowers reports about 17,470 planted acres and roughly 570 vineyards, most held by family farmers, spread across twelve approved appellations. Anderson Valley is the best known, and Mendocino Ridge is the only non-contiguous appellation in the United States.",
      "What sets the county apart for many buyers is organic farming. The grower group reports that about 25 percent of Mendocino's wine grapes are certified organic, and that the county holds about one third of all organic wine grape acreage in California. Pinot Noir, Cabernet Sauvignon, Zinfandel, Merlot and Syrah are the most common reds, with Chardonnay and Sauvignon Blanc the leading whites.",
      "If organic or sustainable fruit matters to your brand, the farming practice filter on HarvestLink lets you narrow Mendocino lots by declared practice. Practices are declared by the seller, so ask for the certificate.",
    ],
    facts: [
      { label: "Planted acres", value: "About 17,470" },
      { label: "Appellations", value: "12 approved" },
      { label: "Certified organic", value: "About 25 percent of wine grapes" },
      { label: "Share of California organic wine grape acres", value: "About one third" },
      { label: "Common varieties", value: "Pinot Noir, Cabernet Sauvignon, Zinfandel, Merlot, Syrah; Chardonnay and Sauvignon Blanc for whites" },
    ],
    buyerNotes: [
      "If you plan an organic or \"made with organic grapes\" claim, ask for the certificate and confirm it covers the specific block and vintage.",
      "Ask which of the twelve appellations the fruit comes from. Anderson Valley and warmer inland areas grow very different wines.",
      "Cooler areas often mean later picks and lower brix, so confirm the brix target and the harvest window.",
      "Compare lots on price per ton or per gallon, and ask whether the price reflects a certification premium.",
    ],
    faq: [
      { q: "How much of Mendocino is organic?", a: "Mendocino Winegrowers reports that about 25 percent of the county's wine grapes are certified organic, and that Mendocino holds about one third of California's organic wine grape acreage. Figures come from the grower group and change over time." },
      { q: "Are farming practices verified on HarvestLink?", a: "No. Practices such as organic, biodynamic or sustainable are declared by the seller. Ask for the certificate, the certifier, the scope and the expiry date before you rely on a claim." },
      { q: "What is Mendocino Ridge?", a: "It is an appellation made up of separate high-elevation areas above the fog line, and it is the only non-contiguous American Viticultural Area in the United States." },
    ],
    sources: [
      { title: "Mendocino Winegrowers: press facts", url: "https://mendowine.com/press-facts-2/" },
      { title: "Mendocino Winegrowers: fact sheet (PDF)", url: "https://mendowine.com/wp-content/uploads/2021/10/Mendocino-Winegrowers-Fact-Sheet.pdf" },
    ],
    related: ["organic-biodynamic-sustainable-wine-labels", "what-is-terroir", "how-to-buy-wine-grapes"],
    alsoSee: ["sonoma-county", "pinot-noir", "zinfandel", "sauvignon-blanc"],
    image: "/images/landing/mendocino-county.webp",
    imageAlt: "Terraced vineyard rows on a hillside with a tall pine tree and blue sky",
  },
  {
    kind: "region",
    slug: "san-luis-obispo-county",
    name: "San Luis Obispo County",
    filterValue: "San Luis Obispo County",
    h1: "Wine Grapes and Bulk Wine from San Luis Obispo County",
    metaTitle: "San Luis Obispo County Wine Grapes & Bulk Wine",
    description: "Find San Luis Obispo County and Paso Robles wine grapes by the ton and bulk wine by the gallon, with Cabernet, Zinfandel and Rhone varieties.",
    quickAnswer:
      "San Luis Obispo County is home to Paso Robles, a large Central Coast appellation established in 1983 that has grown from about 5,000 vineyard acres to more than 40,000. Cabernet Sauvignon is the most widely planted grape, with Zinfandel as the heritage variety and more than 40 varieties grown overall.",
    intro: [
      "Paso Robles is the county's best-known appellation, and it has grown quickly. When it was established in 1983 it had about 17 wineries and 5,000 vineyard acres, with Zinfandel as the heritage grape. Today it is reported to have more than 200 wineries and roughly 40,000 vineyard acres, and it is about three times the size of Napa. About 95 percent of its wineries are family owned.",
      "The variety list is unusually wide. More than 40 varieties are grown, including Cabernet Sauvignon (the most widely planted), Zinfandel, Merlot, Syrah, Grenache, Petite Sirah, Chardonnay and a long list of Rhone and Italian varieties. Cooler coastal parts of the county, such as Edna Valley, are known for Chardonnay and Pinot Noir.",
      "That range makes the county useful for blenders and brands that want several varieties from one region. Lots on HarvestLink are listed by the ton for grapes and by the gallon for bulk wine, openly or under NDA.",
    ],
    facts: [
      { label: "Paso Robles AVA established", value: "1983, with about 17 wineries and 5,000 vineyard acres" },
      { label: "Paso Robles today", value: "More than 200 wineries and about 40,000 vineyard acres" },
      { label: "Varieties grown", value: "More than 40; Cabernet Sauvignon is the most widely planted" },
      { label: "Heritage grape", value: "Zinfandel" },
      { label: "Family-owned wineries", value: "About 95 percent" },
    ],
    buyerNotes: [
      "Paso Robles is a very large appellation with a wide range of soils and temperatures. Ask which part of it the fruit or wine comes from.",
      "For Rhone and Italian varieties, ask for the clone and the vine age, since supply of a specific clone can be limited.",
      "For coastal fruit such as Chardonnay or Pinot Noir, ask about the harvest window and brix, which can differ a lot from warmer inland sites.",
      "Confirm whether a per-ton or per-gallon price is delivered or FOB, since freight from Paso Robles to a Bay Area or Southern California winery is a real cost.",
    ],
    faq: [
      { q: "Is Paso Robles the same as San Luis Obispo County?", a: "No. Paso Robles is one large appellation inside San Luis Obispo County. The county also includes other growing areas, such as Edna Valley on the cooler coast." },
      { q: "What grape is Paso Robles best known for?", a: "Cabernet Sauvignon is the most widely planted, and Zinfandel is the heritage grape. The area also grows many Rhone and Italian varieties." },
      { q: "How do I get notified about new lots?", a: "Save a search on this page or on the Grapes or Bulk Wine page, and HarvestLink emails you once a day when a new matching lot is listed." },
    ],
    sources: [
      { title: "Wikipedia: Paso Robles AVA", url: "https://en.wikipedia.org/wiki/Paso_Robles_AVA" },
      { title: "Wine Spectator: The ABCs of Paso Robles", url: "https://www.winespectator.com/articles/abcs-paso-robles" },
    ],
    related: ["how-to-buy-wine-grapes", "how-to-buy-bulk-wine", "what-is-brix-in-winemaking"],
    alsoSee: ["santa-barbara-county", "zinfandel", "cabernet-sauvignon", "syrah"],
    image: "/images/landing/san-luis-obispo-county.webp",
    imageAlt: "A large oak tree standing above golden vineyard rows in Paso Robles wine country",
  },
  {
    kind: "region",
    slug: "santa-barbara-county",
    name: "Santa Barbara County",
    filterValue: "Santa Barbara County",
    h1: "Wine Grapes and Bulk Wine from Santa Barbara County",
    metaTitle: "Santa Barbara County Wine Grapes & Bulk Wine",
    description: "Buy or sell Santa Barbara County wine grapes and bulk wine, from cool-climate Pinot Noir and Chardonnay to warmer-site Syrah and Bordeaux varieties.",
    quickAnswer:
      "Santa Barbara County has seven appellations and unusual east-west valleys that pull Pacific fog inland. The cooler west suits Chardonnay and Pinot Noir, while the warmer east suits Bordeaux and Rhone varieties. Where a vineyard sits along that line matters more than the county name.",
    intro: [
      "Most of California's coastal ranges run north to south. In Santa Barbara County the valleys run east to west, which lets Pacific breezes and fog travel a long way inland. The result is a steep temperature gradient: the cooler western areas are well suited to Chardonnay and Pinot Noir, while the warmer eastern areas ripen Bordeaux and Rhone varieties.",
      "The county has seven official appellations: Santa Maria Valley, Santa Ynez Valley, Sta. Rita Hills, Ballard Canyon, Los Olivos District, Happy Canyon of Santa Barbara and Alisos Canyon. Santa Maria Valley has roughly 7,500 planted acres and Sta. Rita Hills about 2,700, and both are known for cool-climate Chardonnay, Pinot Noir and Syrah.",
      "Because conditions change over short distances, buyers do better asking for the specific appellation and site than treating the county as one style. Lots on HarvestLink are listed by the ton and by the gallon, and sellers can list confidentially under NDA.",
    ],
    facts: [
      { label: "Appellations", value: "Seven, including Santa Maria Valley, Sta. Rita Hills and Santa Ynez Valley" },
      { label: "Geography", value: "East-west transverse valleys that draw in Pacific fog" },
      { label: "Cooler west", value: "Chardonnay and Pinot Noir" },
      { label: "Warmer east", value: "Bordeaux and Rhone varieties" },
      { label: "Planted acres", value: "Santa Maria Valley about 7,500; Sta. Rita Hills about 2,700" },
    ],
    buyerNotes: [
      "Ask exactly where the vineyard sits. A Sta. Rita Hills Pinot Noir and a warm eastern Cabernet are very different products.",
      "Cool sites often pick later and lower in sugar, so confirm the brix target and how the harvest window is set.",
      "Ask about yields and crop load for premium Pinot Noir and Chardonnay, since these affect both quality and price.",
      "For bulk wine, ask for lab analysis (ABV, total sulfites, pH) on the actual lot, and whether it can be labeled with an appellation.",
    ],
    faq: [
      { q: "Why is Santa Barbara County good for Pinot Noir and Chardonnay?", a: "Its valleys run east to west, so cool Pacific air and fog reach far inland. The cooler western areas ripen fruit slowly, which suits Chardonnay and Pinot Noir." },
      { q: "Does Santa Barbara County grow Bordeaux and Rhone varieties?", a: "Yes. The warmer eastern part of the county is well suited to Bordeaux and Rhone varieties such as Cabernet, Merlot and Syrah." },
      { q: "How many appellations does it have?", a: "Seven: Santa Maria Valley, Santa Ynez Valley, Sta. Rita Hills, Ballard Canyon, Los Olivos District, Happy Canyon of Santa Barbara and Alisos Canyon." },
    ],
    sources: [
      { title: "Wikipedia: Santa Maria Valley AVA", url: "https://en.wikipedia.org/wiki/Santa_Maria_Valley_AVA" },
      { title: "Wikipedia: Sta. Rita Hills AVA", url: "https://en.wikipedia.org/wiki/Sta._Rita_Hills_AVA" },
      { title: "Wikipedia: Santa Ynez Valley AVA", url: "https://en.wikipedia.org/wiki/Santa_Ynez_Valley_AVA" },
    ],
    related: ["what-is-terroir", "what-is-brix-in-winemaking", "how-to-buy-wine-grapes"],
    alsoSee: ["san-luis-obispo-county", "pinot-noir", "chardonnay", "syrah"],
    image: "/images/landing/santa-barbara-county.webp",
    imageAlt: "Fog settling over coastal hills and the sea near Santa Barbara at sunrise",
  },
  {
    kind: "region",
    slug: "san-joaquin-county",
    name: "San Joaquin County",
    filterValue: "San Joaquin County",
    h1: "Wine Grapes and Bulk Wine from San Joaquin County",
    metaTitle: "San Joaquin County Wine Grapes & Bulk Wine (Lodi)",
    description: "Find San Joaquin County and Lodi wine grapes by the ton and bulk wine by the gallon, a large-volume region known for Zinfandel and sustainable farming.",
    quickAnswer:
      "San Joaquin County holds much of the Lodi appellation, recognized in 1986. Lodi has grown from about 39,000 wine grape acres in 1991 to more than 100,000 and has around 750 growers. It is a high-volume source of fruit and bulk wine, known for Zinfandel and for its Lodi Rules sustainability program.",
    intro: [
      "Lodi is the region most buyers mean when they search San Joaquin County. The Lodi appellation was recognized in February 1986 and spans San Joaquin and Sacramento counties. The Lodi Winegrape Commission reports that wine grape acreage has grown from about 39,000 acres in 1991 to more than 100,000, and it represents roughly 750 growers.",
      "The scale matters for buyers. A large, established grower base means volume for both premium and everyday wines, and it is a common source of fruit for blends and bulk wine. Lodi has a long history with Zinfandel, and the commission's own pest-management work grew into the Lodi Rules for Sustainable Winegrowing, a third-party certification you can ask a grower about.",
      "On HarvestLink, San Joaquin County lots are listed by the ton for grapes and by the gallon for bulk wine. Sellers can list openly or confidentially under NDA.",
    ],
    facts: [
      { label: "Lodi appellation recognized", value: "February 1986" },
      { label: "Wine grape acreage", value: "From about 39,000 acres (1991) to more than 100,000" },
      { label: "Growers", value: "About 750" },
      { label: "Best-known grape", value: "Zinfandel, with many other varieties grown" },
      { label: "Sustainability program", value: "Lodi Rules for Sustainable Winegrowing" },
    ],
    buyerNotes: [
      "Ask whether the fruit or wine is Lodi appellation. The appellation crosses county lines, so the county alone does not tell you.",
      "If sustainability matters to your brand, ask whether the vineyard is Lodi Rules certified and request the certificate.",
      "For bulk wine, ask about blend composition, ABV and total sulfites, and whether the lot is single variety or a blend.",
      "Volume lots often sell on a per-ton or per-gallon price that moves with the market, so confirm the price basis and timing.",
    ],
    faq: [
      { q: "Is Lodi in San Joaquin County?", a: "Mostly. The Lodi appellation spans San Joaquin and Sacramento counties, so a lot can be Lodi appellation without being entirely in one county." },
      { q: "What are the Lodi Rules?", a: "They are a sustainable winegrowing certification program that grew out of pest-management protocols developed by the Lodi Winegrape Commission." },
      { q: "Is San Joaquin County a good source of bulk wine?", a: "It is a large-volume region with a big grower base, and many buyers source fruit and wine there. Quality and price still vary by lot, so ask for samples and lab analysis." },
    ],
    sources: [
      { title: "Lodi Winegrape Commission: history of the Lodi AVA", url: "https://www.lodiwine.com/blog/A-history-of-Lodi-winegrowing--part-5---establishment-of-the-Lodi-AVA" },
      { title: "Lodi Winegrape Commission: viticultural area", url: "https://www.lodiwine.com/About/Place/Viticultural-Area" },
    ],
    related: ["how-to-buy-bulk-wine", "organic-biodynamic-sustainable-wine-labels", "what-is-bulk-wine"],
    alsoSee: ["zinfandel", "merlot", "cabernet-sauvignon", "sonoma-county"],
    image: "/images/landing/san-joaquin-county.webp",
    imageAlt: "Long rows of vines stretching across a flat field at sunset in California",
  },
  {
    kind: "region",
    slug: "yamhill-county",
    name: "Yamhill County",
    filterValue: "Yamhill County",
    h1: "Wine Grapes and Bulk Wine from Yamhill County",
    metaTitle: "Yamhill County Wine Grapes & Bulk Wine (Willamette)",
    description: "Find Yamhill County wine grapes and bulk wine from the Willamette Valley, Oregon's Pinot Noir heartland, including Dundee Hills and Yamhill-Carlton.",
    quickAnswer:
      "Yamhill County sits in the Willamette Valley, established in 1983 and famous for Pinot Noir. It holds much of Dundee Hills, Yamhill-Carlton, McMinnville and Ribbon Ridge. Yamhill-Carlton alone has about 2,844 planted acres and 127 vineyards, mostly Pinot Noir, Pinot Gris and Chardonnay.",
    intro: [
      "The Willamette Valley is Oregon's main wine region, and Pinot Noir is what it is best known for. The valley's appellation dates to 1983, and in 2004 growers and wineries obtained smaller appellations for the northern hillsides, including Dundee Hills, Yamhill-Carlton, McMinnville, Ribbon Ridge, Eola-Amity Hills and Chehalem Mountains. Several of these lie wholly or partly in Yamhill County.",
      "The scale of the sub-appellations is modest. Yamhill-Carlton covers about 8,500 acres with about 2,844 planted across 127 vineyards, growing mainly Pinot Noir, Pinot Gris and Chardonnay. Dundee Hills covers about 6,490 acres with about 1,300 planted. Smaller vineyards and hillside sites mean supply of any one appellation is limited.",
      "On HarvestLink, Yamhill County lots are listed by the ton for grapes and by the gallon for bulk wine, and sellers can list under NDA to keep the vineyard name private.",
    ],
    facts: [
      { label: "Willamette Valley AVA", value: "Established 1983" },
      { label: "Yamhill-Carlton", value: "About 8,500 acres, about 2,844 planted, 127 vineyards" },
      { label: "Dundee Hills", value: "About 6,490 acres, about 1,300 planted" },
      { label: "Main varieties", value: "Pinot Noir, Pinot Gris, Chardonnay" },
      { label: "Sub-appellations nearby", value: "Dundee Hills, Yamhill-Carlton, McMinnville, Ribbon Ridge, Eola-Amity Hills, Chehalem Mountains" },
    ],
    buyerNotes: [
      "Appellations do not follow county lines. Ask which one the fruit belongs to, and do not assume a Yamhill County lot is Yamhill-Carlton.",
      "For Pinot Noir, ask the clone and the block, since these shape the style and the price far more than the county does.",
      "Confirm the farming practice and request certificates if you want to claim organic or biodynamic.",
      "Small supply means good lots move quickly, so a saved search can help you see them first.",
    ],
    faq: [
      { q: "Is Yamhill County the same as the Willamette Valley?", a: "No. The Willamette Valley is a large appellation that covers several counties. Yamhill County contains parts of it, including several of its smaller appellations." },
      { q: "What is Yamhill-Carlton known for?", a: "Mainly Pinot Noir, along with Pinot Gris and Chardonnay, grown on hillsides. It has about 127 vineyards on about 2,844 planted acres." },
      { q: "Can I buy Oregon Pinot Noir grapes by the ton here?", a: "Yes, when a grower lists a lot. Set up a saved search for Yamhill County and Pinot Noir, and HarvestLink emails you when a new match appears." },
    ],
    sources: [
      { title: "Wikipedia: Willamette Valley AVA", url: "https://en.wikipedia.org/wiki/Willamette_Valley_AVA" },
      { title: "Wikipedia: Yamhill-Carlton AVA", url: "https://en.wikipedia.org/wiki/Yamhill-Carlton_AVA" },
      { title: "Wikipedia: Dundee Hills AVA", url: "https://en.wikipedia.org/wiki/Dundee_Hills_AVA" },
    ],
    related: ["what-is-terroir", "how-to-buy-wine-grapes", "red-wine-vs-white-wine-how-they-are-made"],
    alsoSee: ["pinot-noir", "pinot-gris", "chardonnay", "walla-walla-county"],
    image: "/images/landing/yamhill-county.webp",
    imageAlt: "Green vineyard rows on rolling hillsides beneath a blue sky",
  },
  {
    kind: "region",
    slug: "yakima-county",
    name: "Yakima County",
    filterValue: "Yakima County",
    h1: "Wine Grapes and Bulk Wine from Yakima County",
    metaTitle: "Yakima County Wine Grapes & Bulk Wine for Sale",
    description: "Source Yakima County wine grapes and bulk wine from Washington's first appellation, from Chardonnay and Riesling to Merlot, Cabernet and Syrah.",
    quickAnswer:
      "The Yakima Valley became Washington's first appellation on March 23, 1983. It has about 18,924 planted vineyard acres and grows a wide mix: Chardonnay, Riesling, Merlot and Cabernet Sauvignon lead, and the warmer sites produce much of the state's Merlot, Cabernet and Syrah.",
    intro: [
      "The Yakima Valley was recognized on March 23, 1983 as the first federally designated wine grape growing region in Washington, and the first north of California. Its total area is about 699,520 acres, of which about 18,924 are planted to vineyards, so grapes are a small part of a large, mostly dry agricultural landscape.",
      "The range of varieties is wide. Chardonnay, Riesling, Merlot and Cabernet Sauvignon are the top varieties, and the warmer sites yield a significant share of Washington's Merlot, Cabernet Sauvignon and Syrah. The appellation also contains sub-appellations, including Snipes Mountain, Rattlesnake Hills, Red Mountain and Candy Mountain, some of which sit in neighboring counties.",
      "Yakima County lots on HarvestLink are listed by the ton for grapes and by the gallon for bulk wine, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Designated", value: "March 23, 1983, Washington's first appellation" },
      { label: "Planted vineyard acres", value: "About 18,924 within about 699,520 total acres" },
      { label: "Top varieties", value: "Chardonnay, Riesling, Merlot, Cabernet Sauvignon" },
      { label: "Warmer sites", value: "Significant shares of Washington's Merlot, Cabernet Sauvignon and Syrah" },
      { label: "Sub-appellations", value: "Snipes Mountain, Rattlesnake Hills, Red Mountain, Candy Mountain" },
    ],
    buyerNotes: [
      "The Yakima Valley appellation extends beyond the county, and some sub-appellations sit in neighboring counties. Ask for the exact appellation and site.",
      "Ask about the irrigation and canopy practices, since these strongly shape ripeness and yield in a dry climate.",
      "For Riesling, confirm the intended style (dry or off-dry) and the acid and sugar targets before you agree to a price.",
      "Ask about winter and frost history for the block, and how the grower handled the most recent cold events.",
    ],
    faq: [
      { q: "Is the Yakima Valley the same as Washington's Columbia Valley?", a: "No. The Yakima Valley is a smaller appellation, and the Columbia Valley is a much larger one. Ask a seller which appellation the fruit or wine actually qualifies for." },
      { q: "What grapes is the Yakima Valley known for?", a: "Its top varieties are Chardonnay, Riesling, Merlot and Cabernet Sauvignon, and its warmer sites produce much of the state's Merlot, Cabernet and Syrah." },
      { q: "How do I get alerts for Washington lots?", a: "Save a search on the Grapes or Bulk Wine page with the region filter set, and HarvestLink emails you once a day when a new matching lot is listed." },
    ],
    sources: [
      { title: "HistoryLink: Yakima Valley designated Washington's first AVA", url: "https://www.historylink.org/file/22768" },
      { title: "Washington State Wine Commission: Yakima Valley AVA", url: "https://www.washingtonwine.org/resource/yakima-valley-ava/" },
    ],
    related: ["how-to-buy-wine-grapes", "what-is-brix-in-winemaking", "spot-vs-forward-wine-grape-contracts"],
    alsoSee: ["walla-walla-county", "riesling", "merlot", "syrah"],
    image: "/images/landing/yakima-county.webp",
    imageAlt: "Aerial view of vineyard blocks in a wide valley with mountains in the distance",
  },
  {
    kind: "region",
    slug: "walla-walla-county",
    name: "Walla Walla County",
    filterValue: "Walla Walla County",
    h1: "Wine Grapes and Bulk Wine from Walla Walla County",
    metaTitle: "Walla Walla County Wine Grapes & Bulk Wine",
    description: "Find Walla Walla County wine grapes by the ton and bulk wine by the gallon from a boutique appellation known for Cabernet, Syrah and Merlot.",
    quickAnswer:
      "The Walla Walla Valley appellation was established in 1984 and spans Washington and Oregon, with about two thirds in Washington. It has roughly 2,933 planted acres and more than 120 wineries. It is small and specialized, known for Cabernet Sauvignon, Syrah, Merlot and Rhone-style blends.",
    intro: [
      "The Walla Walla Valley appellation is unusual because it crosses a state line. Established in 1984, it covers about 300,000 acres in a diamond shape in southeastern Washington and northeastern Oregon, with about two thirds of the land in Washington.",
      "The vineyard area is small, about 2,933 planted acres, but the region has more than 120 wineries, including some of the oldest in Washington. That combination, limited fruit and many wineries, tends to make grape supply competitive. The region is known for Cabernet Sauvignon, Syrah and Merlot, and for Rhone-style blends.",
      "Because the appellation includes Oregon land, it is worth confirming which side of the state line a lot comes from, since some wine can carry the state name only if enough of the fruit is from that state. Lots on HarvestLink are listed by the ton and the gallon, openly or under NDA.",
    ],
    facts: [
      { label: "Established", value: "1984" },
      { label: "Area", value: "About 300,000 acres across Washington and Oregon" },
      { label: "Planted acres", value: "About 2,933" },
      { label: "Wineries", value: "More than 120" },
      { label: "Known for", value: "Cabernet Sauvignon, Syrah, Merlot and Rhone-style blends" },
    ],
    buyerNotes: [
      "Ask which side of the state line the vineyard is on. It can affect how the wine may be labeled.",
      "Supply is limited, so expect competition for good blocks and consider a multi-year arrangement if you need consistency.",
      "For Syrah and Cabernet, ask about the clone, the vine age and the crop load.",
      "Ask about winter cold events and how they affected the vintage you are buying.",
    ],
    faq: [
      { q: "Is Walla Walla in Washington or Oregon?", a: "Both. The Walla Walla Valley appellation covers land in southeastern Washington and northeastern Oregon, with about two thirds of its area in Washington." },
      { q: "What is Walla Walla known for?", a: "Cabernet Sauvignon, Syrah and Merlot, along with Rhone-style blends, from a small area with more than 120 wineries." },
      { q: "Why is supply limited?", a: "Only about 2,933 acres are planted, and many wineries compete for that fruit. A saved search helps you see new lots as soon as they are listed." },
    ],
    sources: [
      { title: "Wikipedia: Walla Walla Valley AVA", url: "https://en.wikipedia.org/wiki/Walla_Walla_Valley_AVA" },
      { title: "Washington State Wine Commission: Walla Walla Valley AVA", url: "https://www.washingtonwine.org/resource/walla-walla-valley-ava/" },
    ],
    related: ["spot-vs-forward-wine-grape-contracts", "how-to-buy-wine-grapes", "what-is-terroir"],
    alsoSee: ["yakima-county", "syrah", "cabernet-sauvignon", "merlot"],
    image: "/images/landing/walla-walla-county.webp",
    imageAlt: "Vineyard rows on a hillside at sunset with dark hills and clouds behind",
  },
  {
    kind: "region",
    slug: "suffolk-county",
    name: "Suffolk County",
    filterValue: "Suffolk County",
    h1: "Wine Grapes and Bulk Wine from Suffolk County (Long Island)",
    metaTitle: "Suffolk County Wine Grapes & Bulk Wine (Long Island)",
    description: "Find Suffolk County, New York wine grapes and bulk wine from Long Island's North Fork, known for Merlot and Cabernet Franc in a maritime climate.",
    quickAnswer:
      "Long Island's wine industry is concentrated in Suffolk County, mostly on the North Fork, which has about 3,000 planted acres and more than three quarters of the island's wine industry. Atlantic breezes keep the climate temperate, and dark-skinned varieties such as Merlot and Cabernet Franc do well.",
    intro: [
      "Long Island is the East Coast's best-known maritime wine region, and nearly all of it lies in Suffolk County. The Long Island appellation has two sub-appellations, the North Fork of Long Island and The Hamptons, Long Island. The North Fork is by far the more planted, with roughly 3,000 acres of vineyards, while The Hamptons has only a few dozen.",
      "The Atlantic Ocean and Long Island Sound moderate temperatures, which gives a long, mild growing season. That maritime climate lets dark-skinned Vitis vinifera varieties such as Merlot and Cabernet Franc ripen well, and the region is known for black-fruit wines with balanced tannins.",
      "Supply is small compared with the West Coast, which makes East Coast lots relatively rare on the market. HarvestLink lists Suffolk County grapes by the ton and bulk wine by the gallon, openly or under NDA.",
    ],
    facts: [
      { label: "Sub-appellations", value: "North Fork of Long Island and The Hamptons, Long Island" },
      { label: "North Fork planted acres", value: "About 3,000" },
      { label: "The Hamptons planted acres", value: "About 55" },
      { label: "Climate", value: "Maritime, moderated by the Atlantic" },
      { label: "Known for", value: "Merlot and Cabernet Franc" },
    ],
    buyerNotes: [
      "Ask which sub-appellation a lot comes from, since the North Fork holds most of the plantings.",
      "Coastal weather can vary a lot from year to year, so ask for the vintage's growing-season notes and the analysis of the actual lot.",
      "For Merlot and Cabernet Franc, ask about the clone, the crop load and the harvest date.",
      "Supply is limited, so confirm quantities and delivery early, and consider how you will transport wine or fruit from the East End.",
    ],
    faq: [
      { q: "Is Long Island wine only in Suffolk County?", a: "Nearly all of Long Island's vineyards are in Suffolk County, and the North Fork holds more than three quarters of the island's wine industry." },
      { q: "What grapes do well on Long Island?", a: "Dark-skinned varieties such as Merlot and Cabernet Franc do particularly well in the temperate, maritime climate." },
      { q: "Why are Long Island lots rare?", a: "Total planted acreage is small compared with California, so fewer lots come to market. Save a search to hear about new ones." },
    ],
    sources: [
      { title: "Wikipedia: North Fork of Long Island AVA", url: "https://en.wikipedia.org/wiki/North_Fork_of_Long_Island_AVA" },
      { title: "Wikipedia: The Hamptons, Long Island AVA", url: "https://en.wikipedia.org/wiki/The_Hamptons,_Long_Island_AVA" },
      { title: "Wine Enthusiast: Long Island region", url: "https://www.wineenthusiast.com/region/long-island/" },
    ],
    related: ["what-is-terroir", "how-to-buy-bulk-wine", "how-much-alcohol-is-in-wine"],
    alsoSee: ["merlot", "cabernet-franc", "yamhill-county", "napa-county"],
    image: "/images/landing/suffolk-county.webp",
    imageAlt: "A green vineyard path between tall vine rows on a sunny day",
  },
];
