import type { LandingPage } from "./types";

export const VARIETY_PAGES: LandingPage[] = [
  {
    kind: "variety",
    slug: "cabernet-sauvignon",
    name: "Cabernet Sauvignon",
    filterValue: "Cabernet Sauvignon",
    h1: "Cabernet Sauvignon Grapes and Bulk Wine for Sale",
    metaTitle: "Cabernet Sauvignon Grapes & Bulk Wine for Sale",
    description: "Buy or sell Cabernet Sauvignon wine grapes priced per ton and bulk Cabernet priced per gallon, from Napa to Paso Robles, including confidential lots.",
    quickAnswer:
      "Cabernet Sauvignon is a red grape with small, thick-skinned berries that give deep color and firm tannin. It ripens late, so it needs a warm, long season. It is the most planted grape in Napa Valley, about 54 percent of vineyards, and in Paso Robles. Compare lots by appellation, vintage and price basis.",
    intro: [
      "Cabernet Sauvignon is a cross of Cabernet Franc and Sauvignon Blanc, a parentage confirmed by DNA work at UC Davis in the 1990s. Its small berries and thick skins give a high ratio of skin to juice, which is why the wines are dark and tannic and age well. It buds and ripens late, so it does best where the season is long and warm enough to fully ripen it.",
      "In this marketplace the variety shows up in most of the big red regions. It covers about 54 percent of Napa Valley's vineyards, is among the top three plantings in Sonoma County at about 12,700 acres, and is the most widely planted grape in Paso Robles. Washington's warmer sites also grow a lot of it. That spread means prices range widely, and the region and the appellation usually explain more of the difference than the variety does.",
      "Grapes on HarvestLink are priced per ton and bulk wine per gallon. Some sellers list confidentially under NDA, in which case you see the variety, vintage, quantity and price, but not the winery or vineyard name.",
    ],
    facts: [
      { label: "Parentage", value: "Cabernet Franc x Sauvignon Blanc" },
      { label: "Berry", value: "Small, thick skin, high skin-to-juice ratio" },
      { label: "Ripening", value: "Late" },
      { label: "Napa Valley plantings", value: "About 54 percent of vineyard acres" },
      { label: "Sonoma County plantings", value: "About 12,700 acres" },
    ],
    buyerNotes: [
      "Ask the exact appellation and vintage. The same variety from a mountain site and a valley floor can differ a lot in style and price.",
      "Ask the brix at harvest or the target, and the pH and acid, not only sugar. Late-ripening fruit can reach high sugar before flavors are ready.",
      "For bulk wine, ask for lab analysis (ABV, total sulfites, volatile acidity) and whether the wine has seen oak.",
      "Compare on the same basis: per ton for grapes, per gallon for wine, delivered or FOB.",
    ],
    faq: [
      { q: "Where does Cabernet Sauvignon come from?", a: "It is a cross of Cabernet Franc and Sauvignon Blanc that arose in southwestern France, and it is now grown across most of the world's wine regions." },
      { q: "Why is Napa Cabernet so expensive?", a: "Supply is small and demand is high. Cabernet covers about 54 percent of Napa Valley vineyards, but the valley is only about 4 percent of California's wine grape harvest, so premium lots are scarce." },
      { q: "How many gallons of Cabernet do I get from a ton?", a: "A common planning figure is about 150 gallons per ton, within a realistic range of roughly 130 to 180, depending on pressing and handling. See the guide linked below for the math." },
    ],
    sources: [
      { title: "Wikipedia: Cabernet Sauvignon", url: "https://en.wikipedia.org/wiki/Cabernet_Sauvignon" },
      { title: "Napa Valley Vintners: fast facts", url: "https://napavalley.wine/fast-facts" },
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
    ],
    related: ["gallons-of-wine-per-ton-of-grapes", "what-is-brix-in-winemaking", "why-napa-valley-wine-is-special"],
    alsoSee: ["napa-county", "merlot", "cabernet-franc", "san-luis-obispo-county"],
    image: "/images/landing/cabernet-sauvignon.webp",
    imageAlt: "A cluster of dark blue Cabernet Sauvignon grapes hanging on the vine",
  },
  {
    kind: "variety",
    slug: "chardonnay",
    name: "Chardonnay",
    filterValue: "Chardonnay",
    h1: "Chardonnay Grapes and Bulk Wine for Sale",
    metaTitle: "Chardonnay Grapes & Bulk Wine for Sale",
    description: "Find Chardonnay wine grapes by the ton and bulk Chardonnay by the gallon from California, Oregon and Washington, including confidential lots.",
    quickAnswer:
      "Chardonnay is a green-skinned grape that adapts to many climates, so it produces lean, mineral wines in cool sites and rich, tropical wines in warm ones. It is the most planted grape in Sonoma County, at about 15,500 acres, and it is used for both still and sparkling wine. Ask for the site and the style.",
    intro: [
      "Chardonnay is a cross of Pinot and Gouais Blanc that comes from Burgundy, and its neutral character is a large part of its appeal. The grape does not have strong aromas of its own, so the wine reflects the climate, the site and the winemaking: oak, malolactic fermentation and time on the lees shape the style more than they do for most whites.",
      "That flexibility explains its footprint. Chardonnay is the most planted variety in Sonoma County at about 15,500 acres, it is a leading white in Mendocino, and it is grown in Santa Barbara, Yamhill County and the Yakima Valley. It also serves as a base for sparkling wine, where the cool-climate fruit is picked earlier at lower sugar and higher acid.",
      "On HarvestLink, Chardonnay grapes are priced by the ton and bulk wine by the gallon, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Skin color", value: "Green" },
      { label: "Origin", value: "Burgundy, France" },
      { label: "Sonoma County plantings", value: "About 15,500 acres, its most planted grape" },
      { label: "Styles", value: "Still (unoaked or oaked) and sparkling base" },
      { label: "Winemaking levers", value: "Oak, malolactic fermentation, lees contact" },
    ],
    buyerNotes: [
      "Say which style you need. Fruit for sparkling base is picked earlier than fruit for a rich, oaked still wine, and the analysis targets differ.",
      "Ask the clone, since Chardonnay clones vary in flavor and yield, and the site's climate.",
      "For bulk wine, ask whether it is finished or unfinished, whether it has seen oak, and whether malolactic fermentation is complete.",
      "Ask for lab analysis (ABV, total sulfites, pH) on the actual lot, and for the malolactic status if it matters to your style.",
    ],
    faq: [
      { q: "What is the difference between oaked and unoaked Chardonnay?", a: "Oaked Chardonnay is fermented or aged in oak barrels and tastes of toast, vanilla and spice. Unoaked is usually made in stainless steel and tastes cleaner and more fruit-driven." },
      { q: "Is Chardonnay used for sparkling wine?", a: "Yes. It is one of the main grapes used for sparkling wine, picked earlier for lower sugar and higher acidity." },
      { q: "How do I get notified about Chardonnay lots?", a: "Save a search from this page, and HarvestLink emails you once a day when a new matching lot is listed." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Chardonnay", url: "https://en.wikipedia.org/wiki/Chardonnay" },
    ],
    related: ["red-wine-vs-white-wine-how-they-are-made", "how-is-wine-made", "how-to-buy-wine-grapes"],
    alsoSee: ["sonoma-county", "santa-barbara-county", "pinot-noir", "sauvignon-blanc"],
    image: "/images/landing/chardonnay.webp",
    imageAlt: "Bunches of green-gold Chardonnay grapes ripening on the vine in the sun",
  },
  {
    kind: "variety",
    slug: "pinot-noir",
    name: "Pinot Noir",
    filterValue: "Pinot Noir",
    h1: "Pinot Noir Grapes and Bulk Wine for Sale",
    metaTitle: "Pinot Noir Grapes & Bulk Wine for Sale",
    description: "Find Pinot Noir wine grapes by the ton and bulk Pinot Noir by the gallon from Sonoma, Santa Barbara and Oregon's Willamette Valley.",
    quickAnswer:
      "Pinot Noir is a thin-skinned red grape that ripens early and is sensitive to climate, so it does best in cool sites. It is the second most planted grape in Sonoma County, at about 13,000 acres, and the signature grape of Oregon's Willamette Valley. Site, clone and yield matter more than the county name.",
    intro: [
      "Pinot Noir is one of the oldest cultivated wine grapes and comes from Burgundy. Its thin skin makes it prone to rot in wet weather, its tight clusters ripen unevenly in heat, and it reflects the site more clearly than most varieties. The result is a grape that rewards careful farming and punishes the wrong climate.",
      "In the regions on this site it shows up in cool places: Sonoma County has about 13,000 acres, Mendocino's Anderson Valley and Santa Barbara's Sta. Rita Hills are known for it, and it is the core of Oregon's Willamette Valley, including Yamhill County. It is also a main grape for sparkling wine, where it is picked early for high acid.",
      "Lots on HarvestLink are priced per ton for grapes and per gallon for bulk wine. Because supply of good blocks is limited, a saved search is the easiest way to see new lots first.",
    ],
    facts: [
      { label: "Skin", value: "Thin, light color" },
      { label: "Origin", value: "Burgundy, France" },
      { label: "Ripening", value: "Early, sensitive to heat and rain" },
      { label: "Sonoma County plantings", value: "About 13,000 acres" },
      { label: "Other uses", value: "Sparkling wine base and rose" },
    ],
    buyerNotes: [
      "Ask the clone and the block. In Pinot Noir these shape the style and price more than almost any other variety.",
      "Ask about crop load and yield per acre. Low yields raise quality and price, and you should know what you are paying for.",
      "Ask about rot and harvest timing for the vintage, especially in wet years.",
      "For bulk wine, ask for the analysis and whether the wine has aged in oak or stainless steel.",
    ],
    faq: [
      { q: "Why is Pinot Noir harder to grow than other reds?", a: "Its thin skins are prone to rot, its tight clusters can ripen unevenly, and it reflects small differences in site. It needs a cool, careful growing season." },
      { q: "Where is Pinot Noir grown on HarvestLink?", a: "Mainly in cool areas: Sonoma County, Mendocino County, Santa Barbara County and Oregon's Yamhill County are the most common." },
      { q: "Can Pinot Noir be used for sparkling wine?", a: "Yes. Along with Chardonnay it is a main grape for sparkling wine, picked earlier at higher acidity." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Willamette Valley AVA", url: "https://en.wikipedia.org/wiki/Willamette_Valley_AVA" },
      { title: "Wikipedia: Pinot noir", url: "https://en.wikipedia.org/wiki/Pinot_noir" },
    ],
    related: ["what-is-terroir", "how-is-wine-made", "how-to-buy-wine-grapes"],
    alsoSee: ["yamhill-county", "sonoma-county", "pinot-gris", "chardonnay"],
    image: "/images/landing/pinot-noir.webp",
    imageAlt: "Tight clusters of dark Pinot Noir grapes on the vine",
  },
  {
    kind: "variety",
    slug: "merlot",
    name: "Merlot",
    filterValue: "Merlot",
    h1: "Merlot Grapes and Bulk Wine for Sale",
    metaTitle: "Merlot Grapes & Bulk Wine for Sale",
    description: "Find Merlot wine grapes by the ton and bulk Merlot by the gallon from California, Washington and New York, including confidential lots.",
    quickAnswer:
      "Merlot is a red grape that ripens earlier than Cabernet Sauvignon and gives softer tannins and plush fruit. It is a staple of Bordeaux blends and grows well in California, Washington and on Long Island. Sonoma County has about 4,200 acres of it. Ask about the site, since Merlot's quality swings widely.",
    intro: [
      "Merlot is a Bordeaux variety, and one of the parents is Cabernet Franc. It buds and ripens earlier than Cabernet Sauvignon, which lowers the risk in cooler or wetter years, and its wines are usually softer, rounder and lower in tannin. It is a workhorse for blending and also stands alone in the right site.",
      "Its footprint reflects that. Sonoma County has about 4,200 acres, Washington's warmer sites produce a significant share of the state's Merlot, and Long Island's maritime climate suits it. Quality and price vary widely, so lots priced by the ton or gallon are best compared with the appellation and the vintage in mind.",
      "HarvestLink lists Merlot grapes by the ton and bulk wine by the gallon, openly or under NDA.",
    ],
    facts: [
      { label: "Type", value: "Red Bordeaux variety" },
      { label: "Ripening", value: "Earlier than Cabernet Sauvignon" },
      { label: "Style", value: "Softer tannin, plush fruit, a common blending partner" },
      { label: "Sonoma County plantings", value: "About 4,200 acres" },
      { label: "Grown well in", value: "California, Washington, Long Island" },
    ],
    buyerNotes: [
      "Ask what the fruit is intended for: a varietal wine or a blending component. It changes what you need from the brix and tannin.",
      "Ask the site and the crop load, since high-yield Merlot can taste thin.",
      "For bulk wine, ask about oak treatment and blend composition.",
      "Ask whether the price is per ton or per gallon and delivered or FOB, and how it compares with Cabernet Sauvignon from the same appellation, which is often priced higher.",
    ],
    faq: [
      { q: "How is Merlot different from Cabernet Sauvignon?", a: "Merlot ripens earlier and gives softer, rounder wines with less tannin. Cabernet ripens later and is darker, firmer and more tannic." },
      { q: "Is Merlot used in blends?", a: "Yes. It is a main part of Bordeaux-style blends and is often blended with Cabernet Sauvignon and Cabernet Franc." },
      { q: "Where can I find Merlot?", a: "Use the buttons below to see current Merlot grape and bulk wine lots, or save a search for an email once a day when a new one is listed." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Merlot", url: "https://en.wikipedia.org/wiki/Merlot" },
    ],
    related: ["how-is-wine-made", "how-to-buy-bulk-wine", "what-is-brix-in-winemaking"],
    alsoSee: ["cabernet-sauvignon", "cabernet-franc", "yakima-county", "suffolk-county"],
    image: "/images/landing/merlot.webp",
    imageAlt: "Ripe dark Merlot grapes hanging in a cluster on the vine",
  },
  {
    kind: "variety",
    slug: "zinfandel",
    name: "Zinfandel",
    filterValue: "Zinfandel",
    h1: "Zinfandel Grapes and Bulk Wine for Sale",
    metaTitle: "Zinfandel Grapes & Bulk Wine for Sale",
    description: "Buy or sell Zinfandel wine grapes by the ton and bulk Zinfandel by the gallon from Lodi, Paso Robles and Sonoma, including old-vine lots.",
    quickAnswer:
      "Zinfandel is a red grape that is genetically the same as Italy's Primitivo, and it is closely tied to California. Its clusters ripen unevenly, which makes harvest timing a skill. Sonoma County has about 4,760 acres, and Lodi and Paso Robles are long-time strongholds. Ask about vine age, since old vines are a selling point.",
    intro: [
      "Zinfandel is genetically the same grape as Italy's Primitivo, and is closely tied to California, where it has been grown for well over a century. Its clusters ripen unevenly, so a single bunch can hold raisined berries next to green ones, and the timing of the pick matters more than it does for most varieties.",
      "It is a stronghold variety in several regions on this site. Sonoma County has about 4,760 acres, Paso Robles has long treated it as its heritage grape, and Lodi is known for it too. Old-vine Zinfandel is a selling point in its own right, but only if the grower can document the age of the vines.",
      "Zinfandel grapes on HarvestLink are priced by the ton and bulk wine by the gallon. Sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Same grape as", value: "Primitivo (Italy)" },
      { label: "Ripening", value: "Uneven within the cluster" },
      { label: "Sonoma County plantings", value: "About 4,760 acres" },
      { label: "Strongholds", value: "Lodi, Paso Robles, Sonoma County" },
      { label: "Selling point", value: "Documented old vines" },
    ],
    buyerNotes: [
      "Ask the vine age and request documentation if you plan to market it as old-vine. There is no legal definition of the term.",
      "Ask about the harvest approach. Uneven ripening means sorting or multiple picks can affect quality and cost.",
      "Ask about brix and expected alcohol, since Zinfandel can reach high sugar.",
      "For bulk wine, ask for the analysis (ABV, total sulfites, volatile acidity) on the actual lot.",
    ],
    faq: [
      { q: "Is Zinfandel the same as Primitivo?", a: "Yes. They are genetically the same grape, though wines labeled Primitivo usually come from southern Italy." },
      { q: "What is white Zinfandel?", a: "It is a pink wine made from Zinfandel grapes by limiting skin contact, and it is a separate style from red Zinfandel." },
      { q: "Does old-vine Zinfandel have a legal definition?", a: "No. The term is not regulated, so ask the grower for the planting date and any records." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Zinfandel", url: "https://en.wikipedia.org/wiki/Zinfandel" },
    ],
    related: ["how-much-alcohol-is-in-wine", "what-is-brix-in-winemaking", "how-to-buy-wine-grapes"],
    alsoSee: ["san-joaquin-county", "san-luis-obispo-county", "sonoma-county", "syrah"],
    image: "/images/landing/zinfandel.webp",
    imageAlt: "Dark Zinfandel grape clusters on an old vine",
  },
  {
    kind: "variety",
    slug: "sauvignon-blanc",
    name: "Sauvignon Blanc",
    filterValue: "Sauvignon Blanc",
    h1: "Sauvignon Blanc Grapes and Bulk Wine for Sale",
    metaTitle: "Sauvignon Blanc Grapes & Bulk Wine for Sale",
    description: "Find Sauvignon Blanc wine grapes by the ton and bulk Sauvignon Blanc by the gallon from Sonoma, Napa, Mendocino and beyond.",
    quickAnswer:
      "Sauvignon Blanc is an aromatic white grape that ripens early and keeps its acidity, which gives crisp, fresh wines. It is also a parent of Cabernet Sauvignon. Sonoma County has about 2,600 acres of it. It is usually made in stainless steel, so tank space and timing are what buyers should plan around.",
    intro: [
      "Sauvignon Blanc is an aromatic white variety from France that ripens relatively early and holds its acid, so the wines are fresh, citrus and herbal in cool sites and more tropical in warmer ones. It is one of the two parents of Cabernet Sauvignon, alongside Cabernet Franc.",
      "It is a smaller planting than Chardonnay in most places, but it is widely grown. Sonoma County has about 2,600 acres, and it is a leading white in Mendocino. Most of it is made in stainless steel for freshness, though some producers use oak or concrete to add texture.",
      "On HarvestLink, Sauvignon Blanc grapes are priced by the ton and bulk wine by the gallon, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Type", value: "Aromatic white" },
      { label: "Ripening", value: "Early, keeps acidity" },
      { label: "Relationship", value: "One parent of Cabernet Sauvignon" },
      { label: "Sonoma County plantings", value: "About 2,600 acres" },
      { label: "Usual style", value: "Crisp, stainless steel" },
    ],
    buyerNotes: [
      "Because harvest is early and the wine is made fresh, plan tank space and the timeline before you agree to a purchase.",
      "Ask the harvest date and the brix, acid and pH, since freshness is the point of the style.",
      "For bulk wine, ask how old the wine is and how it has been stored. Aromatic whites lose freshness with age and oxygen.",
      "Ask whether the lot is finished and clarified, and get the lab analysis.",
    ],
    faq: [
      { q: "Is Sauvignon Blanc related to Cabernet Sauvignon?", a: "Yes. Cabernet Sauvignon is a cross of Sauvignon Blanc and Cabernet Franc." },
      { q: "Is Sauvignon Blanc usually oaked?", a: "Most is made in stainless steel to keep it fresh, though some winemakers use oak to add texture." },
      { q: "Why does age matter for bulk Sauvignon Blanc?", a: "The aromas that define the style fade with time and oxygen, so ask for the vintage, storage and a fresh sample." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Sauvignon blanc", url: "https://en.wikipedia.org/wiki/Sauvignon_blanc" },
    ],
    related: ["red-wine-vs-white-wine-how-they-are-made", "how-to-buy-bulk-wine", "sulfites-in-wine"],
    alsoSee: ["chardonnay", "sonoma-county", "mendocino-county", "pinot-gris"],
    image: "/images/landing/sauvignon-blanc.webp",
    imageAlt: "Pale green Sauvignon Blanc grapes with leaves on the vine",
  },
  {
    kind: "variety",
    slug: "syrah",
    name: "Syrah",
    filterValue: "Syrah",
    h1: "Syrah Grapes and Bulk Wine for Sale",
    metaTitle: "Syrah Grapes & Bulk Wine for Sale",
    description: "Buy or sell Syrah wine grapes by the ton and bulk Syrah by the gallon from Santa Barbara, Paso Robles, Washington and Sonoma.",
    quickAnswer:
      "Syrah is a red grape from the Rhone Valley of France, also sold as Shiraz. It makes dark, peppery, savory wines and grows well in both cool and warm sites, from Santa Barbara's Sta. Rita Hills to Washington's Walla Walla. Sonoma County has about 1,380 acres. Compare on site, since style shifts with climate.",
    intro: [
      "Syrah is the same grape as Shiraz. It comes from the northern Rhone Valley, where it makes dark, savory, peppery wines, and it has become a fixture in California and Washington. Cooler sites give more pepper, olive and floral notes, and warmer sites give riper, darker fruit.",
      "It appears in several regions on this site. Santa Barbara's Sta. Rita Hills and Santa Maria Valley are known for cool-climate Syrah, Walla Walla and the Yakima Valley grow it in Washington, and Sonoma County has about 1,380 acres. It is also a frequent partner in Rhone-style blends with Grenache and Mourvedre.",
      "On HarvestLink, Syrah grapes are priced by the ton and bulk wine by the gallon, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Also called", value: "Shiraz" },
      { label: "Origin", value: "Northern Rhone Valley, France" },
      { label: "Style", value: "Dark, peppery, savory; floral in cool sites" },
      { label: "Sonoma County plantings", value: "About 1,380 acres" },
      { label: "Known areas", value: "Sta. Rita Hills, Paso Robles, Walla Walla" },
    ],
    buyerNotes: [
      "Ask the site's climate. Cool-site and warm-site Syrah are very different products.",
      "Ask the clone and vine age, and whether the wine is intended for a varietal bottling or a Rhone-style blend.",
      "Ask about crop load and harvest date, since the peppery character fades if fruit hangs too long.",
      "For bulk wine, ask whether it is a single-vineyard Syrah or a blend, how much oak it has seen, and for the lab analysis.",
    ],
    faq: [
      { q: "Is Syrah the same as Shiraz?", a: "Yes. Syrah is the name used in France and by many American producers, and Shiraz is the name used in Australia and South Africa." },
      { q: "Where does Syrah grow best?", a: "It does well in both cool and warm sites, such as Santa Barbara's cooler valleys and Washington's Walla Walla, giving different styles in each." },
      { q: "Is Syrah used in blends?", a: "Yes, often with Grenache and Mourvedre in Rhone-style blends." },
    ],
    sources: [
      { title: "Sonoma County Winegrowers: About", url: "https://sonomawinegrape.org/about-scw/" },
      { title: "Wikipedia: Syrah", url: "https://en.wikipedia.org/wiki/Syrah" },
    ],
    related: ["what-is-terroir", "how-to-buy-wine-grapes", "how-is-wine-made"],
    alsoSee: ["santa-barbara-county", "walla-walla-county", "san-luis-obispo-county", "zinfandel"],
    image: "/images/landing/syrah.webp",
    imageAlt: "Deep purple Syrah grape clusters hanging among green leaves",
  },
  {
    kind: "variety",
    slug: "riesling",
    name: "Riesling",
    filterValue: "Riesling",
    h1: "Riesling Grapes and Bulk Wine for Sale",
    metaTitle: "Riesling Grapes & Bulk Wine for Sale",
    description: "Find Riesling wine grapes by the ton and bulk Riesling by the gallon from Washington's Yakima Valley and New York's Finger Lakes.",
    quickAnswer:
      "Riesling is an aromatic white grape from Germany that ripens late but tolerates cold, and it keeps high acidity even when ripe. It can be made bone dry, off-dry or sweet. It is one of the top grapes of Washington's Yakima Valley. Decide the style first, since the sugar and acid targets differ.",
    intro: [
      "Riesling comes from Germany's Rhine region, and it is prized because it stays high in acid even when fully ripe, which lets it carry sweetness without tasting heavy. It also buds late and tolerates cold winters well, which is why it grows where other quality varieties struggle.",
      "In this marketplace its main strongholds are Washington and New York. It is one of the top varieties in the Yakima Valley, and it is a signature white in the cold-climate Finger Lakes region. Styles range from bone dry to sweet, so buyers should decide the style before they compare prices.",
      "On HarvestLink, Riesling grapes are priced by the ton and bulk wine by the gallon. Sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Origin", value: "Germany" },
      { label: "Acidity", value: "High, even when ripe" },
      { label: "Cold tolerance", value: "Good" },
      { label: "Styles", value: "Dry, off-dry and sweet" },
      { label: "Known for on HarvestLink", value: "Yakima Valley, Washington" },
    ],
    buyerNotes: [
      "Decide dry, off-dry or sweet first. Residual sugar, acid and brix targets differ, and a bulk lot can be either.",
      "For bulk wine, ask for the residual sugar in grams per liter along with ABV and total sulfites.",
      "Ask the harvest date and the site, since Riesling picked earlier is leaner and picked later is riper and sweeter.",
      "Ask how the wine was stored, since aromatic whites suffer with oxygen and warm storage.",
    ],
    faq: [
      { q: "Is Riesling always sweet?", a: "No. It can be made bone dry, off-dry or sweet. Its high acidity balances the sugar, so even a sweeter Riesling can taste fresh." },
      { q: "Why is Riesling grown in cold regions?", a: "It buds late and tolerates cold winters, and it keeps its acidity in cool climates, so it suits places like the Yakima Valley and the Finger Lakes." },
      { q: "What should I ask about bulk Riesling?", a: "Ask for the residual sugar, ABV, total sulfites and the storage history, and get a sample from the lot." },
    ],
    sources: [
      { title: "Washington State Wine Commission: Yakima Valley AVA", url: "https://www.washingtonwine.org/resource/yakima-valley-ava/" },
      { title: "Wikipedia: Riesling", url: "https://en.wikipedia.org/wiki/Riesling" },
    ],
    related: ["what-is-brix-in-winemaking", "how-to-buy-bulk-wine", "sulfites-in-wine"],
    alsoSee: ["yakima-county", "chardonnay", "pinot-gris", "sauvignon-blanc"],
    image: "/images/landing/riesling.webp",
    imageAlt: "A cluster of golden Riesling grapes on a vine in sunlight",
  },
  {
    kind: "variety",
    slug: "cabernet-franc",
    name: "Cabernet Franc",
    filterValue: "Cabernet Franc",
    h1: "Cabernet Franc Grapes and Bulk Wine for Sale",
    metaTitle: "Cabernet Franc Grapes & Bulk Wine for Sale",
    description: "Find Cabernet Franc wine grapes by the ton and bulk Cabernet Franc by the gallon from Long Island, California, Washington and beyond.",
    quickAnswer:
      "Cabernet Franc is a red grape from France and a parent of both Cabernet Sauvignon and Merlot. It ripens earlier and handles cold better than Cabernet Sauvignon, so it does well in cooler climates like Long Island. It makes fragrant, medium-bodied wines with red fruit and herbal notes.",
    intro: [
      "Cabernet Franc is one of the founding grapes of Bordeaux. It is a parent of Cabernet Sauvignon, which it created with Sauvignon Blanc, and of Merlot. Compared with Cabernet Sauvignon it ripens earlier and copes better with cool weather, and its wines are lighter, more fragrant and more herbal.",
      "That cold tolerance makes it a good fit for cooler places. It is a signature red on Long Island's North Fork, and it is grown in California, Washington and the Finger Lakes. It is used as a single variety and as a blending partner, adding perfume and lift to Cabernet and Merlot blends.",
      "On HarvestLink, Cabernet Franc grapes are priced by the ton and bulk wine by the gallon, openly or under NDA. Volume is smaller than for the major reds, so a saved search is useful.",
    ],
    facts: [
      { label: "Relationship", value: "Parent of Cabernet Sauvignon and Merlot" },
      { label: "Ripening", value: "Earlier than Cabernet Sauvignon" },
      { label: "Cold tolerance", value: "Better than Cabernet Sauvignon" },
      { label: "Style", value: "Fragrant, medium-bodied, red fruit and herbal notes" },
      { label: "Known areas", value: "Long Island, California, Washington, Finger Lakes" },
    ],
    buyerNotes: [
      "Ask whether the fruit or wine is for a single-variety bottling or for blending, since demands on color and tannin differ.",
      "Ask the harvest date and how ripe the fruit was. Underripe Cabernet Franc tastes green and leafy.",
      "Ask the site, since cool and warm regions give very different wines.",
      "For bulk wine, ask about oak, blend composition and the lab analysis.",
    ],
    faq: [
      { q: "How is Cabernet Franc different from Cabernet Sauvignon?", a: "Cabernet Franc ripens earlier, tolerates cold better and makes lighter, more fragrant wines. Cabernet Sauvignon is darker, firmer and more tannic." },
      { q: "Is Cabernet Franc used in blends?", a: "Yes. It is a common partner for Cabernet Sauvignon and Merlot in Bordeaux-style blends." },
      { q: "Where does Cabernet Franc do well?", a: "Cooler regions such as Long Island's North Fork and the Finger Lakes do well, along with parts of California and Washington." },
    ],
    sources: [
      { title: "Wikipedia: Cabernet Franc", url: "https://en.wikipedia.org/wiki/Cabernet_Franc" },
      { title: "Wine Enthusiast: Long Island region", url: "https://www.wineenthusiast.com/region/long-island/" },
    ],
    related: ["how-is-wine-made", "how-to-buy-bulk-wine", "what-is-terroir"],
    alsoSee: ["cabernet-sauvignon", "merlot", "suffolk-county", "napa-county"],
    image: "/images/landing/cabernet-franc.webp",
    imageAlt: "A close cluster of blue-purple Cabernet Franc grapes on the vine",
  },
  {
    kind: "variety",
    slug: "pinot-gris",
    name: "Pinot Gris",
    filterValue: "Pinot Gris",
    h1: "Pinot Gris Grapes and Bulk Wine for Sale",
    metaTitle: "Pinot Gris Grapes & Bulk Wine for Sale",
    description: "Find Pinot Gris wine grapes by the ton and bulk Pinot Gris by the gallon from Oregon's Willamette Valley, California and Washington.",
    quickAnswer:
      "Pinot Gris, called Pinot Grigio in Italy, is a grey-pink-skinned mutation of Pinot Noir that makes crisp, light whites. It is one of the three main grapes of Oregon's Yamhill-Carlton area. Style depends on the site and the picking date, so decide between a light, fresh wine and a richer one first.",
    intro: [
      "Pinot Gris is a color mutation of Pinot Noir, with grey to pinkish skins that give the wine a slightly copper tone if it gets skin contact. The name is the French one. The same grape is called Pinot Grigio in Italy, and the two labels generally point to a style: Grigio for crisp and light, Gris for rounder and richer.",
      "In this marketplace Oregon is the main source. Yamhill-Carlton lists Pinot Gris alongside Pinot Noir and Chardonnay as a leading grape, and it grows across the Willamette Valley, as well as in California and Washington. It is normally made in stainless steel, so timing and tank space matter.",
      "On HarvestLink, Pinot Gris grapes are priced by the ton and bulk wine by the gallon, and sellers can list openly or under NDA.",
    ],
    facts: [
      { label: "Also called", value: "Pinot Grigio" },
      { label: "Relationship", value: "Color mutation of Pinot Noir" },
      { label: "Skin", value: "Grey to pinkish" },
      { label: "Key region", value: "Oregon's Willamette Valley, including Yamhill-Carlton" },
      { label: "Usual style", value: "Crisp to rich, usually unoaked" },
    ],
    buyerNotes: [
      "Decide the style first. A light Grigio-style wine and a rich Gris-style wine are picked and handled differently.",
      "Ask whether any skin contact was used, since it changes color and texture.",
      "For bulk wine, ask the vintage and storage history, since aromas fade with age and oxygen.",
      "Ask for the ABV, total sulfites and pH on the actual lot, and for a sample you can taste before you commit.",
    ],
    faq: [
      { q: "Is Pinot Gris the same as Pinot Grigio?", a: "Yes. It is the same grape, and the two names usually signal a style: Grigio is typically lighter and crisper, and Gris richer." },
      { q: "Why is Pinot Gris not white?", a: "The grape has grey to pinkish skins because it is a color mutation of Pinot Noir, but the juice is clear, so most wines are white." },
      { q: "Where is Pinot Gris grown on HarvestLink?", a: "Most commonly in Oregon's Willamette Valley, including Yamhill County, and also in California and Washington." },
    ],
    sources: [
      { title: "Wikipedia: Yamhill-Carlton AVA", url: "https://en.wikipedia.org/wiki/Yamhill-Carlton_AVA" },
      { title: "Wikipedia: Pinot gris", url: "https://en.wikipedia.org/wiki/Pinot_gris" },
    ],
    related: ["red-wine-vs-white-wine-how-they-are-made", "how-is-wine-made", "how-to-buy-wine-grapes"],
    alsoSee: ["yamhill-county", "pinot-noir", "riesling", "chardonnay"],
    image: "/images/landing/pinot-gris.webp",
    imageAlt: "Grey-pink Pinot Gris grapes ripening on a vine",
  },
];
